
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cciymjqkuqojzidqprbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjaXltanFrdXFvanppZHFwcmJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMDEyNzMsImV4cCI6MjA1OTU3NzI3M30.B4xSl4SfgI8NDBGKBBRe0SzyHhn5kP-fdBVUTgPGZ84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// This is a workaround for TypeScript until the Supabase types are regenerated
// It extends the existing profile type to include otp_enabled
declare module '@/integrations/supabase/types' {
  interface ProfilesRow {
    otp_enabled?: boolean;
  }
}
